[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/atletas"
  to = "/.netlify/functions/atletas"
  status = 200

[[redirects]]
  from = "/api/escalar"
  to = "/.netlify/functions/escalar"
  status = 200
