[build]
  publish = "."
  functions = "netlify/functions"

[functions."escalar"]
  timeout = 30

[functions."atletas"]
  timeout = 20

[[redirects]]
  from = "/api/atletas"
  to = "/.netlify/functions/atletas"
  status = 200

[[redirects]]
  from = "/api/escalar"
  to = "/.netlify/functions/escalar"
  status = 200
